[functions]
  directory = "./src/functions"

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Headers = "Content-Type, Authorization"
